name: Health Check

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual trigger

jobs:
  run-health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust if needed

      - name: Install Dependencies
        run: npm install  # Only needed if you use external packages

      - name: Run Health Check Script
        run: node healthCheck.js
